# Generated by Django 3.0.5 on 2020-06-15 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminInv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=10)),
                ('fullName', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Administrator',
        ),
    ]
