# Generated by Django 3.0.5 on 2020-06-15 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminInv', '0003_auto_20200615_0816'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
