# Generated by Django 3.0.5 on 2020-06-15 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminInv', '0005_user_sessionid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sessionid',
            field=models.CharField(max_length=50),
        ),
    ]
