# Generated by Django 3.0.5 on 2020-06-15 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminInv', '0006_auto_20200615_1434'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='sessionid',
            new_name='sesskey',
        ),
    ]
