# Generated by Django 3.0.7 on 2020-06-19 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminInv', '0009_auto_20200619_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=30, unique='True'),
        ),
    ]
